### ISSUE TITLE
PG

### ISSUE THREAD

**Issue by shiningwhh** [whaios/showdocdb#2]

**Comment by shiningwhh** [comment]
使用脚本上传PG库，表注释及字段注释丢失
PG版本：14

**Comment by whaios** [comment]
SELECT table_name FROM information_schema.TABLES WHERE TABLE_SCHEMA = $1

**Comment by whaios** [comment]
查询表：SELECT table_name FROM information_schema.TABLES WHERE TABLE_SCHEMA = $1

**Comment by whaios** [comment]
查询表和字段使用的sql如下，你能提供下PG下能查询注释的sql么
![image](https://user-images.githubusercontent.com/19703913/205602973-82dd9e1b-c26b-4ebb-afc2-5d6316a813d6.png)
