### ISSUE TITLE
PG15.1导入后缺少表和字段注释

### ISSUE THREAD

**Issue by zhaoguo2008** [whaios/showdocdb#4]
之前看了关闭的问题sql，可以查出来数据，但是没有备注信息【表和字段】；
使用下面的sql可以查出备注信息
【表备注】
SELECT
	relname AS tabname,
	CAST ( obj_description ( relfilenode, 'pg_class' ) AS VARCHAR ) AS COMMENT
FROM
	pg_class C 
WHERE
	relkind = 'r' 
	AND relname NOT LIKE'pg_%' 
	AND relname NOT LIKE'sql_%' 
ORDER BY
	relname

【表字段备注】
SELECT
 A.attname AS field_name,-- 字段名
 t.typname as typename,    --字段类型
 NULLIF(information_schema._pg_char_max_length(A.atttypid, A.atttypmod), -1) AS maxlen,  -- 字符串最大长度
 col_description ( A.attrelid, A.attnum ) AS COMMENT,   -- 字段备注
 format_type ( A.atttypid, A.atttypmod ) AS TYPE,
 A.attnotnull AS NOTNULL ,  -- 是否非空
 A.atthasdef  --是否存在默认值
FROM
	pg_class AS C,
	pg_attribute AS A ,
	pg_type as T
WHERE
	C.relname = 'plan' 
	AND A.attrelid = C.oid 
	AND A.atttypid= T.oid
	AND A.attnum > 0
	AND NOT A.attisdropped

**Comment by whaios** [comment]
[v1.1.0](https://github.com/whaios/showdocdb/releases/tag/v1.1.0) 版本已更新
